# created by eselect-repo

[guru]
location = /var/db/repos/guru
sync-type = git
sync-uri = https://github.com/gentoo-mirror/guru.git

[hyproverlay]
location = /var/db/repos/hyproverlay
sync-type = git
sync-uri = https://codeberg.org/hyproverlay/hyproverlay.git

[pentoo]
location = /var/db/repos/pentoo
sync-type = git
sync-uri = https://github.com/pentoo/pentoo-overlay.git

[steam-overlay]
location = /var/db/repos/steam-overlay
sync-type = git
sync-uri = https://github.com/anyc/steam-overlay.git

[mrpenguin]
location = /var/db/repos/mrpenguin
sync-type = git
sync-uri = https://github.com/MrPenguin07/ebuilds.git
