#!/usr/sbin/nft -f

flush ruleset

table inet filter {

    chain input {
        type filter hook input priority 0;
        policy drop;
        
	# Allow loopback tracfic
        iif lo accept
        
	# Allow replies to estalished connections
        ct state established,related accept

	# Drop malformed packets
        ct state invalid drop

	# Allow ping (IPv4)
        ip protocol icmp accept

	# Allow ping and essential ICMv6
        ip6 nexthdr icmpv6 accept

	# Allow  SSH
        tcp dport 22 accept
    }

    chain forward {
        type filter hook forward priority 0;
        policy drop;
    }

    chain output {
        type filter hook output priority 0;
        policy accept;
    }
}
