#-----------------------------
# unbind & bind
#-----------------------------
# prefix key
unbind C-b

# Bind new prefix
set-option -g prefix C-Space

#-----------------------------
# Mapping of keys
#-----------------------------
# kbd for floax-bind
set -g @floax-bind 'F'
# rebinding the previous-window KBG taken by floax-bind
bind p previous-window

# Send C-SPC key to program (because the prefix key is set to C-SPC some
# programes except this)
bind C-Space send-prefix

# vim motion to change panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Config reload
bind-key r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded."

# resizing
bind -r H resize-pane -L 1
bind -r J resize-pane -D 1
bind -r K resize-pane -U 1
bind -r L resize-pane -R 1
# Use this for manual resizing
# select-layout even-horizontal
# select-layout even-vertival
# select-layout tiled

#-----------------------------
# Mode
#-----------------------------
set -g mode-keys emacs


#-----------------------------
# Status line
#-----------------------------
set-option -g status-style bg=magenta,fg=black


set -g status-right "#(/home/wolfer/.tmux/plugins/tmux-continuum/scripts/continuum_save.sh)#{?window_bigger,[#{window_offset_x}#,#{window_offset_y}] ,}\"#{=21:pane_title}\""


#-----------------------------
# Options & settings
#-----------------------------
# scrolling
set-option -g history-limit 10000

# mouse emable
set -g mouse on
# use prifix-[ to enter into tmux copy mode and q to exit it.

# copy paste enabling
# Allow OSC 52 clipboard passthrough
set -g allow-passthrough on
# Explicitly enable clipboard support
set -g set-clipboard on
# Tell tmux that Alacritty supports OSC 52
set -as terminal-features ',alacritty:clipboard'


#-----------------------------
# tpm & plugins
#-----------------------------
#tpm
set -g @plugin 'tmux-plugins/tpm'

# plugins
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'alexwforsythe/tmux-which-key'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'omerxx/tmux-floax'
# set -g @plugin 'dracula/tmux' 

run '~/.tmux/plugins/tpm/tpm'


# Some KBD related plug-ins managment
# $ Ctrl+b I   # Install plugins (capital I)
# $ Ctrl+b U   # Update all plugins
# $ Ctrl+b alt+u   # Remove unused plugins